# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - release
notifications:
  email: true
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/aoboturov/PMTK4BasicModels.jl.git"); Pkg.clone("https://github.com/aoboturov/PMTK4Stats.jl.git"); Pkg.clone(pwd()); Pkg.build("PMTK4BookDemos"); Pkg.test("PMTK4BookDemos"; coverage=true)'
